db:
  image: postgres
  environment:
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_USER=postgres
web:
  build: .
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db/postgres
    - MIX_ENV
    - SECRET_KEY_BASE
  links:
    - db
  ports:
    - '4000:4000'
  volumes:
    - .:/app
